/**
 * Color picker API
 * Api used by the color picker miniapp to communicate the selected color
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */
import {expect} from 'chai';
import ColorPickerRequests  from '../../src/api/ColorPickerRequests';
import ColorPickerEvents  from '../../src/api/ColorPickerEvents';

describe('ColorPickerApi', function(){
  let requests;
  let events;
  beforeEach(function() {
    requests = new ColorPickerRequests({
        registerHandler(){
        },
        sendRequest(){
        }
    });
    events = new ColorPickerEvents({
        registerEventListener(){
        },
        emitEvent(){
        }
    });

  });


    describe('colorSelected', function() {
        it('should emit event colorSelected successfully', (done)=> {
        //uncomment below and update the code to test colorSelected
        //register listener.
        //events.addColorSelectedEventListener(()=>done());
        //emit event.
        //events.emitColorSelected(selectedColor: string);
        //});
        done();
        });
    });

    describe('getSelectedColor', function() {
      it('should send request getSelectedColor successfully', ()=> {
        //uncomment below and update the code to test getSelectedColor
        //return requests.getSelectedColor().then(response=> {
        //  if (error) throw error;
        //  expect(response).to.be();
        //});

      });
    });

});
